# Generated by Django 2.1.3 on 2018-12-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='populate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
