# Generated by Django 2.1.3 on 2018-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20181210_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(default='static/images/NIKE-AIR-270.jpg', upload_to='static/images/profile_pic'),
        ),
    ]
