# Generated by Django 2.1.3 on 2018-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20181210_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(default='static/images/image.png', upload_to='static/images/profile_pic'),
        ),
    ]
