# Generated by Django 2.1.3 on 2018-12-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_auto_20181219_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentresponse',
            name='date',
        ),
    ]
